// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// This class is used to get the current platform and return the Firebase options for that platform.
class DefaultFirebaseOptions { 
  static FirebaseOptions get currentPlatform { // This method is used to get the current platform and return the Firebase options for that platform.
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// The Firebase options for the different platforms.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuM6S_lmu4pS7HlKodRmu9Olr_iZHils', // The Unique Identifier, API key for the Firebase project. (API request key)
    appId: '1:179232677382:web:6d60759b15ce12fe94ed87', // The Unique Identifier, App ID for the Firebase project.
    messagingSenderId: '179232677382', // ID is used  to identify the sender of a message.
    projectId: 'mynotes-buck', // ID is used to identify the project in Firebase accros all .
    authDomain: 'mynotes-buck.firebaseapp.com', // The domain of the Firebase project.
    storageBucket: 'mynotes-buck.appspot.com', // The storage bucket of the Firebase project. used to store files.
    measurementId: 'G-FDSCS0K4NF', // The Unique Measurement ID for the Firebase project. Measures interaction with your app.
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3HfNBfu95j_4PxMk8gF4WcKUWYz_a-A',
    appId: '1:179232677382:android:0345072602dcc74f94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3FsSXGi4lE79EUx97bvBsHToHEBpLKg',
    appId: '1:179232677382:ios:0cceb6c2237e672b94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
    iosBundleId: 'com.firstproject.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3FsSXGi4lE79EUx97bvBsHToHEBpLKg',
    appId: '1:179232677382:ios:0cceb6c2237e672b94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
    iosBundleId: 'com.firstproject.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIuM6S_lmu4pS7HlKodRmu9Olr_iZHils',
    appId: '1:179232677382:web:9b5e2b6b1862363794ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    authDomain: 'mynotes-buck.firebaseapp.com',
    storageBucket: 'mynotes-buck.appspot.com',
    measurementId: 'G-6DFBGSBQMV',
  );
}