// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuM6S_lmu4pS7HlKodRmu9Olr_iZHils',
    appId: '1:179232677382:web:6d60759b15ce12fe94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    authDomain: 'mynotes-buck.firebaseapp.com',
    storageBucket: 'mynotes-buck.appspot.com',
    measurementId: 'G-FDSCS0K4NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3HfNBfu95j_4PxMk8gF4WcKUWYz_a-A',
    appId: '1:179232677382:android:0345072602dcc74f94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3FsSXGi4lE79EUx97bvBsHToHEBpLKg',
    appId: '1:179232677382:ios:0cceb6c2237e672b94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
    iosBundleId: 'com.firstproject.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3FsSXGi4lE79EUx97bvBsHToHEBpLKg',
    appId: '1:179232677382:ios:0cceb6c2237e672b94ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    storageBucket: 'mynotes-buck.appspot.com',
    iosBundleId: 'com.firstproject.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIuM6S_lmu4pS7HlKodRmu9Olr_iZHils',
    appId: '1:179232677382:web:9b5e2b6b1862363794ed87',
    messagingSenderId: '179232677382',
    projectId: 'mynotes-buck',
    authDomain: 'mynotes-buck.firebaseapp.com',
    storageBucket: 'mynotes-buck.appspot.com',
    measurementId: 'G-6DFBGSBQMV',
  );
}